
/** 
Block Structure class 
*/

import { Element } from "./Element";
import { ElementRange } from "./ElementRange";

export class Block {
  blockId: number; // sequential id
  blockName: string | undefined;  //generated by feature Naming activity Or by user input 
  blockContent: Map<string, ElementRange[]>; // // Map <variantId , lines of the file>
  tfIdfWordCloud: any[] = [];
  colorOfBlock: string = "#082567";

  constructor(blockId: number, blockName: string | undefined, blockContent: Map<string, ElementRange[]>, colorOfBlock: string) {
    this.blockId = blockId;
    this.blockName = blockName;
    this.blockContent = blockContent;
    if (colorOfBlock) {
      this.colorOfBlock = colorOfBlock;
    }
  }

  addElementRangeToBlock(partOfBlock: Map<string, ElementRange[]>) {
    partOfBlock.forEach((value: ElementRange[], variantId: string) => {
      value.forEach(item => this.blockContent?.get(variantId)?.push(item));
    });
  }

  /**
   * Checks if intersectionId equals to this.blockId
   * @param intersection <VariantId, ElementRange>
   * @returns 
   */
  havingSameBlockId(intersection: Map<string, ElementRange[]>): boolean {
    let resullt = "";
    let allVariants = Array.from(intersection.keys());
    allVariants.sort((a, b) => a.localeCompare(b));
    resullt = allVariants.toString();

    let thisAllVariatns = Array.from(this.blockContent.keys());
    thisAllVariatns.sort((a, b) => a.localeCompare(b));
    let resullt2 = thisAllVariatns.toString();

    return resullt === resullt2;
  }
}

