
/** 
Block Structure class 
*/

import { Element } from "./Element";

export class Block {
    blockId : string ; // Block Id composed of variants ids
    blockName : string | undefined;  //generated by feature Naming activity Or by user input 
    blockContent : Map<string,Element[]|undefined> ; // // Map <filename , lines of the file>
    
    constructor(blockId: string,blockName:string|undefined,blockContent:Map<string,Element[]>) {
        this.blockId = blockId ;
        this.blockName = blockName ;
        this.blockContent = blockContent ; 
      }
}

